### ISSUE TITLE
Jastrow/Klein Dictionaries

### ISSUE THREAD

**Issue by yehosef** [Sefaria/Sefaria-Data#128]
I see from https://blog.sefaria.org/blog/2018/11/12/jastrow-and-klein-dictionaries that you have imported these two dictionaries, but I can't find them in the data or export repositories.  

Where can I find them or how can I regenerate them?

**Comment by edamboritz** [comment]
Hi, Unfortunately we do not support exporting the data from the dictionaries to our export repository. We may do so in the future. 
In the meantime you can get the data for entries from our API paths. 
I will just note here that the Klein dictionary is available under the [CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) license.

**Comment by yehosef** [comment]
Thanks - I guess what I'm wondering is, is the Jastrow dictionary text extraction from the PDF or were you given the structured text?  If it is extracted, is the code for extraction in one of the public repos or is it in a private repo?

It seems we can get the data from the mongo dump in the lexicon_entries - I was just curious about seeing the process you used to extract/clean it.

**Comment by jcuenod** [comment]
https://github.com/Sefaria/Sefaria-Data/commit/2151151c70752bd6853658a20f2c86061f0462b7

**Comment by avimar** [comment]
> In the meantime you can get the data for entries from our API paths.

It's nikkud-sensitive though?

This works to lookup "א": https://www.sefaria.org/api/texts/Jastrow%20%D7%90

This works to do a lookup for אֶבְגִּינוֹס:
https://www.sefaria.org/api/texts/Jastrow%20%D7%90%D6%B6%D7%91%D6%B0%D7%92%D6%B4%D6%BC%D7%99%D7%A0%D7%95%D6%B9%D7%A1

But אבגינוס return {"error": "Word not found in Jastrow"}

And then we have entries with multiple versions, which I have to look up all versions of the word because אַבָּא returns nothing.
אַבָּא I
אַבָּא II
אַבָּא III

How do you run the typical lookup that seems to manage this OK? Where's a translation or normalization layer?
