### ISSUE TITLE
Wrong location for an opening bracket in Nehemiah 7

### ISSUE THREAD

**Issue by baruchel** [Sefaria/Sefaria-Data#74]
_[Working with the JSON version of JPS]_ In Nehemiah 7, verse 67 ends with the two characters `[a`. A quick glance at a scan from the 1917 printed edition shows that:

    * the `a` character (for a footnote) should be removed
    * the `[` character should be moved to the beginning of the following verse (verse 68).

Regards, tb.

**Comment by bachrach44** [comment]
Neither of those characters exists in Nehemiah 7:67. Please provide the details of what you're looking at - text version and exact location.

**Comment by baruchel** [comment]
In the following file: https://github.com/Sefaria/Sefaria-Data/blob/master/sources/JPS1917/json/NEHEMIAH.txt I see `[a` at the end of 7:67 and I think something should be done about that, shouldn't it? Regards.

**Comment by bachrach44** [comment]
I think you're looking for this repo:
https://github.com/Sefaria/Sefaria-Export

The Sefaria-Data repo is the repo we use for importing. Included in there are lots of files and scripts which were used to import data. Some of them, like the files from the 1917 JPS you're looking at are basically data dumps from elsewhere that we later fixed up once they got to Sefaria. Some of the content there woud have been fixed by a script or manually through the UI. The export repo is the one that exports our actual data set and includes the most up to date data we have for everything. That's the one you should use if you're trying to use Sefaria data for some purpose.
